### ISSUE TITLE
Update to 1.0.1.

### ISSUE THREAD

**Issue by tidux** [flathub/org.strawberrymusicplayer.strawberry#10]
New upstream release.

https://github.com/strawberrymusicplayer/strawberry/releases

**Comment by Lunarequest** [comment]
We already ship it https://github.com/flathub/org.strawberrymusicplayer.strawberry/blob/1de827ed2b96e88b7db1c9752f8537be2ecb7e77/org.strawberrymusicplayer.strawberry.yaml#L108
