### ISSUE TITLE
[Gnome 42] Render artifacts at bottom of main window

### ISSUE THREAD

**Issue by Mershl** [flathub/org.strawberrymusicplayer.strawberry#21]
## Description
The strawberry main window renders a few extra lines at the bottom which seem to show a past framebuffer.

The issue is reproduciable on a fresh installation of Silverblue 36 with no theme applied (default Adwaita theme) on latest strawberry release on flathub.

Tested on `mutter-42.0-5.fc36.x86_64` (Wayland), `org.freedesktop.Platform.GL.default 21.3.8`, `AMD Ryzen 3500U (Vega iGPU)`.

## Screencast
https://user-images.githubusercontent.com/520251/164891084-506d2bb8-ecf7-4738-b4c9-2f27a2df0d9a.mp4

**Comment by Lunarequest** [comment]
Its an upstream issue. Not flatpak
