### ISSUE TITLE
No audio CD support?

### ISSUE THREAD

**Issue by oseez** [flathub/org.strawberrymusicplayer.strawberry#22]
Libcdio was compiled to disable CD access?  A music player intentionally unable to play CDs?!

**Comment by Lunarequest** [comment]
I'd also like to point out Clementine also does this here https://github.com/flathub/org.clementine_player.Clementine/blob/master/org.clementine_player.Clementine.yaml#L87-L96

**Comment by jonaski** [comment]
Those options doesn't disable CD access, they only disable building utilities, only the library is used by strawberry which is built even with all the `--without` options:

```
  --without-cd-drive      don't build program cd-drive (default with)
  --without-cd-info       don't build program cd-info (default with)
  --without-cdda-player   don't build program cdda-player (default with)
  --without-cd-read       don't build program cd-read (default with)
  --without-iso-info      don't build program iso-info (default with)
  --without-iso-read      don't build program iso-read (default with)
```
