### ISSUE TITLE
flatpack update not working

### ISSUE THREAD

**Issue by MaxSTM** [flathub/org.strawberrymusicplayer.strawberry#43]
This was reported on the project github

[Flatpak Refresh of Strawberry 1.0.14 fails with server 404](https://github.com/strawberrymusicplayer/strawberry/issues/1127)

please have a look when you have time

**Comment by CPacaud123** [comment]
I have this too. Seems like a lot of people are having this issue.

**Comment by Lunarequest** [comment]
Looks like flathub had maintenance and not everything came back up

**Comment by Lunarequest** [comment]
I've published a refresh, it shouldn't take to log for it to propagate

**Comment by CPacaud123** [comment]
Thanks!
