### ISSUE TITLE
KDE 6.2 runtime breaks qgnomeplatform themeing

### ISSUE THREAD

**Issue by Mershl** [flathub/org.strawberrymusicplayer.strawberry#5]
`5.15-21.08` introduced qgnomeplatform themeing last month which worked beautifully on Strawberry. Yesterdays update does no longer support/breaks it. The app is now shown in normal breeze light theme, on a Gnome system with Dark (Yaru) theme. 

#### Before update:
< will edit >

#### After 6.2 update:
![image](https://user-images.githubusercontent.com/520251/144230906-e5ba52e5-4ea6-4948-9d2b-86daa75bfd82.png)

**Comment by Lunarequest** [comment]
We switched to qt6. It is not a issue on strawberry's side. Your theme must support qt6, most do not. closing based on above

**Comment by Mershl** [comment]
Makes sense. To report it to the correct location: What does "support qt6" mean for a gtk/a GNOME theme?

**Comment by Lunarequest** [comment]
Not sure how qgomeplatform works so can't coment
