### ISSUE TITLE
[Question] Can I upgrade this with "flatpak update"?

### ISSUE THREAD

**Issue by abceleung** [flathub/org.strawberrymusicplayer.strawberry#50]
Hi, just a question: 

In Flathub the latest version is 1.0.0 (released a year ago), but the manifest file here gets updates often.

Can `flatpak update` update this package? Or does the package update itself?

**Comment by Lunarequest** [comment]
so the package semi updates it self, we have a bot that autoupdates the image, the manifest simple builds it the version info on the flathub page comes from upstreams metainfo file. flatpak update will install the latest version
