### ISSUE TITLE
Recent version missing KDE Shortcut (KGlobalAccel) option

### ISSUE THREAD

**Issue by deanrih** [flathub/org.strawberrymusicplayer.strawberry#61]
As discussed [here](https://github.com/strawberrymusicplayer/strawberry/issues/1289), it seems the new version doesn't have the KDE Shortcut (KGlobalAccel) option or maybe don't ship with it as dependency and it didn't detect it?

I first realize this when after an update (which is a while ago, I just get the time to report it now) I couldn't bring up the app window with a shortcut even though it's already set up. It does work now using the X11 option, but now missing the option in the KDE Shortcut settings.

Previously,
1. Open Strawberry window
2. Check the "Use KGlobalAccel" and uncheck the "Use X11"
3. Set up some shortcut like Show/Hide
4. Use the shortcut to show/hide the window
5. Also, the shortcut setting is now created on KDE settings

Now the previously created shortcut on KDE Setting didn't do anything and nor actually pressing the shortcut since the "KGlobalAccel" option is missing, at least until you enable the "Use X11 shortcut"

**Comment by Lunarequest** [comment]
seems we need to add `--talk-name=org.kde.kglobalaccel` to fix this. will add  open a pr shortly
