### ISSUE TITLE
EBU R 128 loudness normalization

### ISSUE THREAD

**Issue by korongmambu** [flathub/org.strawberrymusicplayer.strawberry#67]
This feature exist from version 1.0.19, but still can't use it

**Comment by Lunarequest** [comment]
if you can figure out what package is needed for it I'll add it to the flatpak

**Comment by korongmambu** [comment]
`libebur128`, please add:
https://github.com/jiixyj/libebur128/archive/refs/tags/v1.2.6.tar.gz

**Comment by Lunarequest** [comment]
added a pr need to wait for the builds to finish and then it can be merged
