### ISSUE TITLE
Strawberry Music Player doesn't start.

### ISSUE THREAD

**Issue by tabetai** [flathub/org.strawberrymusicplayer.strawberry#69]
I got this error while trying to start application:

`/app/bin/strawberry: symbol lookup error: /app/bin/strawberry: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API
`

System Information:
Flatpak Version: 1.14.4-2
Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-13-generic (64-bit)
Graphics Platform: X11

**Comment by regunakyle** [comment]
Same error:
```
❯ flatpak run org.strawberrymusicplayer.strawberry
/app/bin/strawberry: symbol lookup error: /app/bin/strawberry: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API
```

System Information:
Flatpak Version: 1.15.4
Operating System: Fedora Linux 38
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.6.3-100.fc38.x86_64 (64-bit)
Graphics Platform: Wayland
