### ISSUE TITLE
fix metadata: unofficial flatpak, own issue tracker

### ISSUE THREAD

**Issue by trytomakeyouprivate** [flathub/org.strawberrymusicplayer.strawberry#74]
The Strawberry Team seems to have no interest in maintaining the Flatpak.

So the metadata should be updated, to refer to this issuetracker instead of theirs.

Also the Metadata doesn't currently align with the new Flathub Guidelines:
- the screenshot has at least themed decorations
- the summary is "A music player and collection organizer", they would probably prefer something like "Play music and organize your collections"

**Comment by Lunarequest** [comment]
it is official and does get help from upstream. it is also verified from upstream

**Comment by trytomakeyouprivate** [comment]
weird...@jonaski told something different in [this issue](https://github.com/strawberrymusicplayer/strawberry/issues/1365)

**Comment by jonaski** [comment]
It's been primarily me working on Strawberry, and there are simply no resources/time for me left to maintain or support a Flatpak package. I do not have knowledge about Flatpak, and not much interest in it either, I never volunteered for it.
I don't know why the Strawberry project became responsible for fixing issues in the metadata for Flatpak.
I see no reason for me to spend time on it, maintaining Strawberry is far too much work for one person already, there are often bugs in Qt that needs to be fixed, or at least reported, several bugs in Qt in the past have prevented use of strawberry, and GStreamer is even worse, I'm already way behind on reporting them. Spending my time on addressing what looks to be a minor issue with the metadata in Flatpak is simply no priority for me at all.
Users reports all sorts of issues to me regarding the Flatpak, even blaming me when the Flatpak servers are down, and get angry when I tell them to report it to Flatpak.
Linux distribution packages in Fedora, Debian, Arch and others are official, but this does not mean that they are maintained by the strawberry project, or that I am responsible for packaging issues. Flatpak is part of packaging system, not a package that you get from the strawberry website or from the GitHub downloads as single file.
If the metadata is taken from the appdata file, then I suggest someone familiar with the Flatpak packaging and guidelines opens a PR with a proposal for changes. I am not even sure what is meant by "themed decorations".

**Comment by trytomakeyouprivate** [comment]
that is totally understandable and I dont want anything from you :D I can fix the metadata when I have time, I just didnt find the file
