### ISSUE TITLE
Add Spotify support via gst-plugins-rs

### ISSUE THREAD

**Issue by TheJanzap** [flathub/org.strawberrymusicplayer.strawberry#91]
In version 1.1.0, Strawberry gained the ability to stream from Spotify. But according to the [wiki](https://wiki.strawberrymusicplayer.org/wiki/Installing_GStreamer_Spotify_plugin), this feature depends on [gst-plugins-rs](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs).

Would it be possible to include this in the Flatpak, either directly or as an optional add-on?

**Comment by TheJanzap** [comment]
I just updated the Flatpak from 1.1.3 to 1.2.3, but the settings page still says that the GStreamer Spotify plugin was not detected. I tried disabling and enabling the Spotify plugin and reauthenticating, but this didn't help.
Is there something I need to do on my end?

**Comment by jonaski** [comment]
Spotify wasn't added, it was incorrectly added as fixed in #93
