### ISSUE TITLE
GStreamer issue when attempting any kind of podcast

### ISSUE THREAD

**Issue by dln949** [flathub/org.strawberrymusicplayer.strawberry#99]
Strawberry 1.1.3 (flatpak) on Ubuntu 22.04, gnome 42.9, wayland.  

For example, when attempting to play this podcast:  https://odysee.com/$/rss/@RobBraxmanTech:6 , I get the following error message, but I have no idea what it means and what I should do:  

Your GStreamer installation is missing a plug-in.

../gst/playback/gsturidecodebin.c(1049): no_more_pads_full (): /GstPlayBin:pipeline-1-pipeline/GstURIDecodeBin:uridecodebin0: no suitable plugins found: ../gst/playback/gstdecodebin2.c(4705): gst_decode_bin_expose (): /GstPlayBin:pipeline-1-pipeline/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0: no suitable plugins found: Missing decoder: application/xml (application/xml) 

Internal data stream error.

../libs/gst/base/gstbasesrc.c(3134): gst_base_src_loop (): /GstPlayBin:pipeline-1-pipeline/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source: streaming stopped, reason not-linked (-1)

**Comment by jonaski** [comment]
Podcasts are not directly supported, if you look at the XML you need to add the actual streams which is found under `<enclosure url`, tags, for example.: `<enclosure url="https://player.odycdn.com/api/v3/streams/free/fad/f6e6798a2307b4db2d857ba8e6ac1dd08b7a1143/5e96e1.mp4" length="983476551" type="video/mp4"/>`
